name: null
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000900'
    - '#888b9b'
    - '#4f6548'
    - '#195cc1'
    - '#e4ded2'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: shares
    item: 'null'
    url: null
