name: null
favicon: null
layout_spectrum: 0.11713
typography_spectrum: 0.41892
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000100'
    - '#725d45'
    - '#fcfffc'
    - '#44241d'
    - '#caa884'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 1
purpose:
  - name: shares
    item: 'null'
    url: null
