name: gbpcosta
favicon: null
layout_spectrum: 0.48423
typography_spectrum: 0.66517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13293d'
    - '#e8f1f2'
    - '#26a09a'
    - '#006494'
    - '#6fbeeb'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: 'null'
    url: null
