name: null
favicon: null
layout_spectrum: 0.13512
typography_spectrum: 0.32883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000110'
    - '#e1fefe'
    - '#5c8c91'
    - '#a1c6dd'
    - '#335e64'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: 'null'
    url: null
